const assert=require('node:assert/strict');const {webcrypto}=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const api=require('../dist/auth-demo.js');
function memory(){const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k),data};}
(async()=>{const local=memory(),session=memory(),auth=api.createStore(local,session,webcrypto);
assert.equal(auth.current(),null);await assert.rejects(auth.register('A','bad','short'));await assert.rejects(auth.register('Demo','bad','test-only-123'));await assert.rejects(auth.register('Demo','demo@example.com','short'));
const profile=await auth.register(' Lupe de prueba ',' DEMO@example.com ','test-only-123');assert.equal(profile.name,'Lupe de prueba');assert.equal(profile.email,'demo@example.com');assert.equal(auth.current().name,profile.name);const stored=JSON.stringify([...local.data]);assert.ok(!stored.includes('test-only-123'));assert.ok(stored.includes('digest'));assert.ok(!JSON.stringify([...session.data]).includes('digest'));
await assert.rejects(auth.register('Otra','demo@example.com','another-test-123'));auth.logout();assert.equal(auth.current(),null);await assert.rejects(auth.login('demo@example.com','incorrecta'));assert.equal(auth.current(),null);await assert.rejects(auth.login('missing@example.com','test-only-123'));await auth.login('DEMO@example.com','test-only-123');assert.equal(auth.current().name,'Lupe de prueba');
const newSession=memory(),otherTab=api.createStore(local,newSession,webcrypto);assert.equal(otherTab.current(),null);await otherTab.login('demo@example.com','test-only-123');assert.equal(otherTab.current().email,'demo@example.com');
auth.logout();auth.google();assert.equal(auth.current().provider,'google-demo');assert.equal(auth.current().email,'demo@example.com');auth.logout();assert.equal(auth.current(),null);
for(const input of ['https://evil.example','//evil.example','javascript:alert(1)','../../outside','constructor','__proto__',null]){assert.equal(api.nextKey(input),'reaccion');assert.equal(api.destination(input),'../index.html');}
assert.equal(api.destination('canasta'),'../atrapar-comida/index.html');assert.equal(api.destination('sopa'),'../sopa/index.html');assert.equal(api.destination('decisiones'),'../decisiones/index.html');
const blocked={getItem(){return null},setItem(){throw Error('Quota exceeded')},removeItem(){throw Error('Blocked')}};const limited=api.createStore(blocked,session,webcrypto);await assert.rejects(limited.register('Demo','another@example.com','test-only-123'),/guardar/);assert.equal(auth.current(),null);
const root=path.resolve(__dirname,'../dist');const pages=['index.html','sopa/index.html','decisiones/index.html','atrapar-comida/index.html','acceso/index.html','cuenta/index.html'];
for(const name of pages){const html=fs.readFileSync(path.join(root,name),'utf8');if(!name.startsWith('acceso/')&&!name.startsWith('cuenta/'))assert.ok(html.includes('data-account-link'));for(const m of html.matchAll(/(?:src|href)="([^\"]+)"/g)){const value=m[1].split(/[?#]/)[0];if(!value||value.includes(':'))continue;assert.ok(fs.existsSync(path.resolve(root,path.dirname(name),decodeURIComponent(value))),name+': '+value);}}
console.log('PASS: registro, validación, correos duplicados, contraseña errónea, sesión, cierre, Google simulado, rutas permitidas, almacenamiento bloqueado y enlaces locales.');
})();
