const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function setup(){const elements=new Map();function el(){return {style:{setProperty(){}},classList:{add(){},remove(){}},setAttribute(){},append(){},addEventListener(){},showModal(){this.open=true},close(){this.open=false},focus(){},querySelector(){return el()},querySelectorAll(){return [el(),el()]},hidden:false,disabled:false}}const document={querySelector(s){if(!elements.has(s))elements.set(s,el());return elements.get(s)},createElement:el,addEventListener(){}};const context=vm.createContext({document,performance:{now:()=>1000},requestAnimationFrame:()=>1,cancelAnimationFrame(){},Math});vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../dist/sueno/game.js'),'utf8'),context);return s=>vm.runInContext(s,context)}
test('quiet room conserves rest and victory ends exactly at 30 seconds',()=>{const run=setup();run('start();nextSpawn=100;advance(31)');assert.equal(run('state'),'won');assert.equal(run('elapsed'),30);assert.equal(run('rest'),100)});
test('active distractions drain, clicking stops drain and prevents duplicate points',()=>{const run=setup();run('start();nextSpawn=100;spawn();advance(1)');assert.equal(run('rest'),98.95);run('disable(objects.findIndex(o=>o.active))');const score=run('score');run('objects.forEach((o,i)=>disable(i));advance(2)');assert.equal(run('rest'),98.95);assert.equal(run('cleared'),1);assert.equal(run('score'),score)});
test('rest exhaustion ends immediately before dawn',()=>{const run=setup();run('start();nextSpawn=100;spawn();spawn();advance(30)');assert.equal(run('state'),'lost');assert.equal(run('rest'),0);assert.ok(run('elapsed')<30)});
test('pause freezes simulation; restart resets counters',()=>{const run=setup();run('start();advance(.5);pause()');const elapsed=run('elapsed');run('advance(20)');assert.equal(run('elapsed'),elapsed);assert.equal(run('state'),'paused');assert.equal(run("$('#pause-dialog').open"),true);run('resume()');assert.equal(run('state'),'playing');assert.equal(run("$('#pause-dialog').open"),false);run('advance(.5)');assert.equal(run('elapsed'),elapsed+.5);run('start()');assert.equal(run('elapsed'),0);assert.equal(run('rest'),100);assert.equal(run('cleared'),0)});
test('moving distraction freezes when stopped; new first distraction differs',()=>{const run=setup();run('start();objects[5].active=true;nextSpawn=100;advance(1);disable(5)');const age=run('objects[5].age');run('advance(1)');assert.equal(run('objects[5].age'),age);run('spawn()');const first=run('previousFirst');run('start();spawn()');assert.notEqual(run('previousFirst'),first)});

test('winnable with 1.5-second reactions across 100 random nights',()=>{for(let trial=0;trial<100;trial++){const run=setup();run('start();for(let i=0;i<1900&&state===\'playing\';i++){advance(1/60);objects.forEach((o,j)=>{if(o.active&&o.age>=1.5)disable(j)});}');assert.equal(run('state'),'won');assert.ok(run('rest')>20);}});
test('ignoring every distraction still loses',()=>{const run=setup();run('start();for(let i=0;i<1900&&state===\'playing\';i++)advance(1/60)');assert.equal(run('state'),'lost');});
